CREATE DATABASE [ICON_CFG_JKT]
ON PRIMARY
(
    NAME = N'ICON_CFG_JKT',
    FILENAME = N'D:\MSSQL\Data\ICON_CFG_JKT.mdf',
    SIZE = 614400KB,
    FILEGROWTH = 65536KB
)
LOG ON
(
    NAME = N'ICON_CFG_JKT_log',
    FILENAME = N'D:\MSSQL\Log\ICON_CFG_JKT_log.ldf',
    SIZE = 102400KB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 65536KB
);
GO

ALTER DATABASE [ICON_CFG_JKT] COLLATE Latin1_General_CI_AS;
GO

ALTER DATABASE [ICON_CFG_JKT] SET RECOVERY SIMPLE;
GO

ALTER DATABASE [ICON_CFG_JKT] SET COMPATIBILITY_LEVEL = 130;
GO
