CREATE DATABASE [ICON_OCS_BDG]
ON PRIMARY
(
    NAME = N'ICON_OCS_BDG',
    FILENAME = N'D:\MSSQL\Data\ICON_OCS_BDG.mdf',
    SIZE = 4988928KB,
    FILEGROWTH = 65536KB
)
LOG ON
(
    NAME = N'ICON_OCS_BDG_log',
    FILENAME = N'D:\MSSQL\Log\ICON_OCS_BDG_log.ldf',
    SIZE = 608192KB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 65536KB
);
GO

ALTER DATABASE [ICON_OCS_BDG] COLLATE Latin1_General_CI_AS;
GO

ALTER DATABASE [ICON_OCS_BDG] SET RECOVERY SIMPLE;
GO

ALTER DATABASE [ICON_OCS_BDG] SET COMPATIBILITY_LEVEL = 130;
GO
