CREATE DATABASE [ICON_OCS_JKT]
ON PRIMARY
(
    NAME = N'ICON_OCS_JKT',
    FILENAME = N'D:\MSSQL\Data\ICON_OCS_JKT.mdf',
    SIZE = 4988928KB,
    FILEGROWTH = 65536KB
)
LOG ON
(
    NAME = N'ICON_OCS_JKT_log',
    FILENAME = N'D:\MSSQL\Log\ICON_OCS_JKT_log.ldf',
    SIZE = 608192KB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 65536KB
);
GO

ALTER DATABASE [ICON_OCS_JKT] COLLATE Latin1_General_CI_AS;
GO

ALTER DATABASE [ICON_OCS_JKT] SET RECOVERY SIMPLE;
GO

ALTER DATABASE [ICON_OCS_JKT] SET COMPATIBILITY_LEVEL = 130;
GO
