CREATE DATABASE [ICON_MM_JKT]
ON PRIMARY
(
    NAME = N'ICON_MM_JKT',
    FILENAME = N'D:\MSSQL\Data\ICON_MM_JKT.mdf',
    SIZE = 52428800KB,
    FILEGROWTH = 65536KB
)
LOG ON
(
    NAME = N'ICON_MM_JKT_log',
    FILENAME = N'D:\MSSQL\Log\ICON_MM_JKT_log.ldf',
    SIZE = 1744832KB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 65536KB
);
GO

ALTER DATABASE [ICON_MM_JKT] COLLATE Latin1_General_CI_AS;
GO

ALTER DATABASE [ICON_MM_JKT] SET RECOVERY SIMPLE;
GO

ALTER DATABASE [ICON_MM_JKT] SET COMPATIBILITY_LEVEL = 130;
GO
