CREATE DATABASE [ICON_MM_BDG]
ON PRIMARY
(
    NAME = N'ICON_MM_BDG',
    FILENAME = N'D:\MSSQL\Data\ICON_MM_BDG.mdf',
    SIZE = 52428800KB,
    FILEGROWTH = 65536KB
)
LOG ON
(
    NAME = N'ICON_MM_BDG_log',
    FILENAME = N'D:\MSSQL\Log\ICON_MM_BDG_log.ldf',
    SIZE = 1744832KB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 65536KB
);
GO

ALTER DATABASE [ICON_MM_BDG] COLLATE Latin1_General_CI_AS;
GO

ALTER DATABASE [ICON_MM_BDG] SET RECOVERY SIMPLE;
GO

ALTER DATABASE [ICON_MM_BDG] SET COMPATIBILITY_LEVEL = 130;
GO
